# ==========================================================
# COLUMN MAPPING
# Excel Column  --> SQL Column
# ==========================================================

COLUMN_MAPPING = {

    # ======================================================
    # MASTER TABLES
    # ======================================================

    "customer_account": {
        "Account Number": "account_number",
        "Old Account Number": "old_account_number",
        "Customer Name": "customer_name",
        "Meter Number": "meter_number",
        "Tariff": "tariff",
        "Contract Status": "contract_status",
    },

    "location": {
        "Region": "region",
        "County": "county",
        "Sector Name": "sector_name",
        "Zone Name": "zone_name",
        "Itinerary": "itinerary",
        "Business Unit": "business_unit",
        "Office Name": "office_name",
        "Reading Unit": "reading_unit",
        "Supply Location": "supply_location",
        "Latitude": "latitude",
        "Longitude": "longitude",
    },

    "meter": {
        "Meter Number": "meter_number",
        "Meter Serial Number": "meter_serial_number",
        "Meter Type": "meter_type",
        "Meter Phase": "meter_phase_type",
        "Model Name": "model_name",
        "Mark Name": "mark_name",
    },

    "staff": {
        "Staff No": "staff_no",
        "Staff": "staff_name",
        "County": "county",
        "Workstation": "workstation",
        "Section Name": "section_name",
    },

    # ======================================================
    # TRANSACTION TABLES
    # ======================================================

    "offline_meters_cycle_reading": {
        "Account Number": "account_number",
        "Meter Number": "meter_number",
        "Staff No": "staff_no",
        "Inspection Date": "inspection_date",
        "Campaign Type": "campaign_type",
        "Inspection Status": "inspection_status",
        "Validation Status": "validation_status",
        "Operation": "operation",
        "Meter Serial Number": "meter_serial_number_input",
        "System Payment": "system_payment",
        "Payment Mode": "payment_mode",
        "Total Reading": "total_reading",
        "High Rate Reading": "high_rate_reading",
        "Low Rate Reading": "low_rate_reading",
        "KVA Reading": "kva_reading",
        "KW Reading": "kw_reading",
        "KVA": "kva",
        "KWH": "kwh",
        "Earth Current": "earth_current",
        "Number of Meters": "number_of_meters_on_site",
        "Overdue Debt": "overdue_debt",
        "Revenue Collected": "revenue_collected",
        "Has Overdue Debt": "has_overdue_debt",
        "Tampered Meter": "tampered_meter",
        "Faulty Meter": "faulty_meter",
        "Idle Meter": "idle_meter",
        "Bypassed Meter": "bypassed_meter",
        "Read Status": "read_status",
        "Remarks": "remarks",
        "SIM Serial": "sim_serial",

        "System Region": "system_region",
        "System County": "system_county",
        "Sys Mtrnumber": "sys_mtrnumber",
        "Sys Accnumber": "sys_accnumber",
        "GlobalID": "globalid",
        "Created User": "created_user",
        "Created Date": "created_date",
        "Last Edited User": "last_edited_user",
        "Last Edited Date": "last_edited_date",
    },

    "offline_smart_meters": {
        "Account Number": "account_number",
        "Staff No": "staff_no",
        "Meter Number": "meter_number",
        "Communication Status": "communication_status",
        "Last Communication Time": "last_communication_time",
        "Latitude": "latitude",
        "Longitude": "longitude",

        "Model Name": "model_name",
        "Meter Phase": "meter_phase",
        "ITIN Type": "itin_type",
        "Contract Type": "contract_type",
        "COD Tariff": "cod_tariff",
        "Feeder ID": "feeder_id",
        "MFC Feeder Name": "mfc_feeder_name",
    },

    "ordinary_debtlist": {
        "Account Number": "account_number",
        "Termination Date": "termination_date",
        "Customer Type": "customer_type",
        "Customer Category": "customer_category",
        "Last Monthly Bill": "last_monthly_bill",
        "Overdue Amount": "overdue_amount",
        "Debt": "debt",
        "Credit": "credit",
        "Total Balance": "total_balance",
        "Max Due Date": "max_due_date",
        "Classification": "classification",
        "Deposit": "deposit",
        "Stima Loan Balance": "stimaloan_balance",
        "Work Order Number": "work_order_number",
        "Work Order Type": "work_order_type",
        "Work Order Status": "work_order_status",
        "Work Order Age Days": "work_order_age_days",

        "Legacy Number": "legacy_number",
        "COD Tarif": "cod_tariff",
        "X Coords": "x_coords",
        "Y Coords": "y_coords",
    },

    "lp_debt": {
        "Account Number": "account_number",
        "Bill Month": "bill_month",
        "Overdue Amount": "overdue_amount",
        "Current Balance": "current_balance",
        "Debt Amount": "debt_amount",
        "Credit Amount": "credit_amount",
        "Total Balance": "total_balance",
        "Last Payment Date": "last_payment_date",
        "Last Payment Amount": "last_payment_amount",
        "Debt Age Days": "debt_age_days",

        "Legacy Number": "legacy_number",
        "VAT": "vat",
        "ADMD": "admd",
        "Avg 6 Month Bill": "avg_6_month_bill",
        "Deposit Amount": "deposit_amount",
        "Guarantee Amount": "guarantee_amount",
    },

    "admd": {
        "Account Number": "account_number",
        "Inspection Date": "inspection_date",
        "Current ADMD": "current_admd",
        "Previous ADMD": "previous_admd",
        "ADMD Variance": "admd_variance",
        "ADMD Status": "admd_status",
        "Remarks": "remarks",

        "NISS": "niss",
        "KVA Demand": "kva_demand",
        "KVA Contract": "kva_contract",
        "Difference": "difference",
        "Meters": "meters",
    },

    "change_of_tariff": {
        "Account Number": "account_number",
        "Previous Tariff": "previous_tariff",
        "New Tariff": "new_tariff",
        "Change Date": "change_date",
        "Reason": "reason_for_change",
        "Approved By": "approved_by",
        "Remarks": "remarks",

        "NISS": "niss",
        "Meters": "meters",
        "Avg Consum": "avg_consumption",
        "Tariff Range": "tariff_range",
    },

    "zero_cons": {
        "Account Number": "account_number",
        "Billing Period": "billing_period",
        "Consecutive Zero Months": "consecutive_zero_months",
        "Average Previous Consumption": "average_previous_consumption",
        "Current Consumption": "current_consumption",
        "Suspected Reason": "suspected_reason",
        "Investigation Status": "investigation_status",
        "Remarks": "remarks",

        "NISS": "niss",
        "Customer Name": "customer_name",
        "Tariff": "tariff",
        "Staff": "staff",
        "Meter": "meter",
        "Total Amount": "total_amount",
        "Invoice Date": "invoice_date",
    },

    "load_factor": {
        "Account Number": "account_number",
        "Analysis Period": "analysis_period",
        "Maximum Demand": "maximum_demand",
        "Average Load": "average_load",
        "Load Factor": "load_factor",
        "Utilization Percentage": "utilization_percentage",
        "Analysis Status": "analysis_status",
        "Remarks": "remarks",

        "NISS": "niss",
        "Staff": "staff",
        "Meter": "meter",
        "Tariff": "tariff",
        "High Rate": "high_rate",
        "Low Rate": "low_rate",
        "KVA Demand": "kva_demand",
        "KW Demand": "kw_demand",
    },

    "pf_1st_time": {
        "Account Number": "account_number",
        "Inspection Date": "inspection_date",
        "Current Power Factor": "current_power_factor",
        "Target Power Factor": "target_power_factor",
        "Reactive Power": "reactive_power",
        "Apparent Power": "apparent_power",
        "PF Status": "pf_status",
        "Recommendation": "recommendation",
        "Remarks": "remarks",

        "Supply": "supply",
        "COD Tariff": "cod_tariff",
        "Staff": "staff",
        "KVA Units": "kva_units",
        "KW Units": "kw_units",
        "HR Units": "hr_units",
        "LR Units": "lr_units",
        "PF Amount": "pf_amount",
    },

    "poor_pf": {
        "Account Number": "account_number",
        "Inspection Date": "inspection_date",
        "Power Factor": "power_factor",
        "Reactive Power": "reactive_power",
        "Apparent Power": "apparent_power",
        "Active Power": "active_power",
        "Power Loss": "power_loss",
        "Penalty Amount": "penalty_amount",
        "Correction Required": "correction_required",
        "Correction Status": "correction_status",
        "Recommendation": "recommendation",
        "Remarks": "remarks",

        "NISS": "niss",
        "Staff": "staff",
        "Tariff": "tariff",
        "Bill Amount": "bill_amount",
        "KVA Demand": "kva_demand",
        "KW Demand": "kw_demand",
        "High Rate": "high_rate",
        "Low Rate": "low_rate",
        "PF Surcharge": "pf_surcharge",
    },

    "cons_deviation": {
        "Account Number": "account_number",
        "Analysis Period": "analysis_period",
        "Previous Consumption": "previous_consumption",
        "Current Consumption": "current_consumption",
        "Consumption Difference": "consumption_difference",
        "Percentage Change": "percentage_change",
        "Deviation Status": "deviation_status",
        "Remarks": "remarks",

        "Avg Consum": "avg_consumption",
        "Current Cycle": "current_cycle",
        "Previous Cycle": "previous_cycle",
        "Percentage Diff": "percentage_diff",
        "ID Payment Form": "id_payment_form",
        "NISS": "niss",
        "Cliente": "cliente",
        "Staff": "staff",
        "Meters": "meters",
        "Tariff": "tariff",
    },

    "postpaid_billing": {
        "Account Number": "account_number",
        "Bill Month": "bill_month",
        "Units Billed": "units_billed",
        "Amount Billed": "amount_billed",
        "Amount Paid": "amount_paid",
        "Balance": "balance",

        "Period": "period",
        "Tariff Desc": "tariff_desc",
        "Classification": "classification",
        "Invoice Date": "invoice_date",
        "Bill Type": "bill_type",
        "Bill Status": "bill_status",
        "Ind Estimated": "ind_estimated",
    },

    "ordinary_acs_meter_rdg": {
        "Account Number": "account_number",
        "Meter Number": "meter_number",
        "Previous Reading": "previous_reading",
        "Current Reading": "current_reading",
        "Consumption": "consumption",
        "Reading Date": "reading_date",
        "Read Status": "read_status",
        "Reader Code": "reader_code",
        "Meter Reader": "meter_reader",
        "Reading From Meter": "reading_from_meter",
        "Previous Value": "previous_value",
        "Estimated Reading": "estimated_reading",
        "Self Read": "self_read",
        "Usage Type": "usage_type",

        "Period": "period",
        "COD Tariff": "cod_tariff",
        "Billing Type": "billing_type",
        "Billed Units": "billed_units",
        "Times Billed Zero": "times_billed_zero",
    },

    "smart_meter_billing": {
        "Account Number": "account_number",
        "Meter Number": "meter_number",
        "Previous Active Energy": "previous_active_energy",
        "Current Active Energy": "current_active_energy",
        "Previous High Rate": "previous_high_rate",
        "Current High Rate": "current_high_rate",
        "Previous Low Rate": "previous_low_rate",
        "Current Low Rate": "current_low_rate",
        "Previous KW": "previous_kw",
        "Current KW": "current_kw",
        "Previous KVA": "previous_kva",
        "Current KVA": "current_kva",
        "Total Consumption": "total_consumption",
        "Total Amount": "total_amount",
        "Read Status": "read_status",

        "Feeder ID": "feeder_id",
        "MFC Feeder Name": "mfc_feeder_name",
    }
}